spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_teahouse?serverTimezone=Asia/Shanghai
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.qf.pojo

voter:
  redis:
    host: 39.99.212.238
    port: 6379
    pass: admin


  aes:
    passkey: dP0ykNOnMdKFaXCIOnXckg==
